#!/bin/sh

cd gettext-0.19.8.1
make clean && make distclean
cd ..

cd glib-2.50.2
make clean && make distclean
cd ..

cd libffi-3.2.1
make clean && make distclean
cd ..

cd libiconv-1.14
make clean && make distclean
cd ..

cd libpng-1.2.57
make clean && make distclean
cd ..

cd pcre-8.40
make clean && make distclean
cd ..

cd qemu-2.8.0
make clean && make distclean
cd ..

rm -rf config-temp
