#!/bin/sh

ANDROID_BUILD=~/dev/android/build
SYSROOT=$ANDROID_BUILD/sysroot

cd gettext-0.19.8.1
make clean && make distclean
cd ..

cd glib-2.50.3
make clean
cd ..

cd libffi-3.2.1
make clean
cd ..
rm -rf ${SYSROOT}/usr/lib/libffi-3.2.1

cd libiconv-1.14
make clean
cd ..

cd libpng-1.2.57
make clean
cd ..

cd pcre-8.40
make clean
cd ..

cd qemu-2.8.0
make clean
cd ..

rm -rf config-temp config.log androidLibs/*
