#!/bin/bash

#Created by fallenworld
#email:fallenworlder@gmail.com

cd gettext-0.19.8.1

ANDROID_BUILD=~/dev/android/build
PATH=$ANDROID_BUILD/bin:$PATH
SYSROOT=$ANDROID_BUILD/sysroot
HOST=arm-linux-androideabi
CFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16"
CXXFLAGS="-std=c++11"
LIBS=
LIBDIRS="-L$ANDROID_BUILD/arm-linux-androideabi/lib -L$(pwd)/gettext-tools/gnulib-lib/.libs"
LDFLAGS="-march=armv7-a -Wl,--fix-cortex-a8 $LIBDIRS"
CONFLAGS="--prefix=${SYSROOT}/usr --host=$HOST"

#configure
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" ./configure $CONFLAGS &&

#make & install
make && make install &&

#copy .so files
cp -fv gettext-runtime/intl/.libs/libintl.so ../androidLibs/
cp -fv gettext-runtime/libasprintf/.libs/libasprintf.so ../androidLibs/
cp -fv gettext-tools/libgettextpo/.libs/libgettextpo.so ../androidLibs/
cp -fv gettext-tools/gnulib-lib/.libs/libgettextlib-0.19.8.1.so ../androidLibs/
cp -fv gettext-tools/src/.libs/libgettextsrc-0.19.8.1.so ../androidLibs/


